version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cesizen_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizen_secret
      POSTGRES_DB: cesizen_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
